---


- name: "loop for preparing virtual server JSON objects, for dRouter {{item.dRouter}}"
  include_tasks: virtual_server.yaml
  with_items: "{{ item.publicAddress }}"
  loop_control:
    loop_var: address_item

