---

- name: retrieve list of existing GSLB subscriptions
  delegate_to: localhost
  uri:
    url: "https://{{F5AAS_SERVER}}/{{API_VERSION}}/svc-subscription/subscriptions?status=_allStatusFilter&account_id={{ACCOUNT_ID}}&service_type=gslb"
    method: GET
    return_content: yes
    status_code: 200
    headers:
      Accept: application/json
      Authorization: "Bearer {{ACCESS_TOKEN}}"
      Host: api.cloudservices.f5.com
  register: f5aas_list_subscriptions

- name: filter list of GSLB subscriptions based on zone name
  set_fact:
    subscription_id: "{{ f5aas_list_subscriptions.json |Â json_query(query) | first | default('') }}"
  vars: 
    query: "subscriptions[?configuration.gslb_service.zone=='{{GSLB_DOMAIN}}'].subscription_id"

- name: delete GSLB subscription
  delegate_to: localhost
  uri:
    url: https://{{F5AAS_SERVER}}/{{API_VERSION}}/svc-subscription/subscriptions/{{subscription_id}}/retire
    method: POST
    return_content: yes
    status_code: 200
    headers:
      Accept: application/json
      Authorization: "Bearer {{ACCESS_TOKEN}}"
  when: subscription_id != ""
  register: f5aas_retire_details

- name: delete GSLB subscription - show return value
  debug:
    msg: "{{ f5aas_retire_details }}"
  when: f5aas_retire_details != "" and VERBOSE == "true"

